blog/apps/noticias/urls.py
from django.urls import path, include
from . import views

app_name = 'noticias'

urlpatterns = [
    
    path('', views.Noticias, name='noticias'),
    path('Detalle/<int:pk>', views.Detalle_Noticias, name='detalle'),    
]

blog/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('registro/', views.Registro.as_view(), name='registro'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth


urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('', views.Home, name='home'),
    path('Nosotros/', views.Nosotros, name='nosotros'),
    
    #URL LOGIN/LOGOUT
    path('login/', auth.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),

    #URL DE APLICACIONES
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/', include('apps.usuarios.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/noticias/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length = 60)
    
    def __str__(self):
        return self.nombre
    

class Noticia(models.Model):
    titulo = models.CharField(max_length = 150)
    cuerpo = models.TextField()
    imagen = models.ImageField(upload_to = 'noticias')
    fecha = models.DateField(auto_now=True)
    categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)    
    
    def __str__(self):
        return self.titulo
    

blog/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 

class Usuario(AbstractUser):
    pass 

blog/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar contraseña', widget=forms.PasswordInput, required=True)
    
    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

blog/apps/noticias/views.py
from django.shortcuts import render
from .models import Noticia
# from django.contrib.auth.decorators import login_required


# @login_required #sirve para que no se pueda acceder a una página sin loguearse
def Noticias(request):
    contexto = {}
    n = Noticia.objects.all() # Retorna una lista de objetos
    contexto['noticias'] = n
    
    return render(request, 'noticias/noticias.html', contexto)

def Detalle_Noticias(request, pk):
    contexto = {}
    n = Noticia.objects.get(pk=pk) # Retorna un solo objeto
    contexto['noticia'] = n
    
    return render(request, 'noticias/detalle.html', contexto)

blog/apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegistroForm

# Create your views here.
class Registro(CreateView):
    #FORMULARIO DJANGO
    form_class = RegistroForm
    success_url = reverse_lazy('login')
    template_name = 'usuarios/registro.html' 

blog/blog/views.py
from django.shortcuts import render

def Home(request):
    return render(request, 'home.html')

def Nosotros(request):
    return render(request, 'nosotros.html')

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>CCCC · {% block titulo %}{% endblock titulo %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    </head>

    <body>
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="facebook" viewBox="0 0 16 16">
                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            </symbol>
            <symbol id="instagram" viewBox="0 0 16 16">
                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            </symbol>
            <symbol id="twitter" viewBox="0 0 16 16">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
            </symbol>
        </svg>

        <header class="sticky-top">
            <nav class="navbar navbar-expand-md navbar-light bg-warning">
                <div class="container-fluid">
                    
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <img src="{% static 'img/logo2.png' %}" alt="" width="40" height="35">
                    </a>
    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
    
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Inicio</a>
                            </li>
    
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'noticias:noticias' %}">Noticias</a>
                            </li>
    
                            <li class="nav-item dropdown">
                                <a class="nav-link active dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Nosotros</a>
    
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item"  href="{% url 'nosotros' %}">Quienes somos</a></li>
                                    <li><a class="dropdown-item" href="#">Que hacemos</a></li>
                                </ul> 
                            </li>
    
                            <li class="nav-item dropdown">
                                <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Contacto</a>
    
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">Telefono</a></li>
                                    <li><a class="dropdown-item" href="#">e-mail</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">Dirección</a></li>
                                </ul>                            
                            </li>
    
                        </ul>
    
                        {% if user.is_authenticated %}
                        Hola <strong>&nbsp;{{ user.username }} &nbsp;</strong>
                        <button class="btn btn-outline-success" type="link">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                        </button>
                        {% else  %}
                        <form class="d-flex btn-group">
                            <button class="btn btn-outline-dark" type="link">
                                <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                            </button>
    
                            <button class="btn btn-success" type="link"><a class="nav-link" href="{% url 'usuarios:registro' %}">Registrarse</a></button>                        
                        </form>
                        {% endif %} 

                    </div>
    
                </div>
            </nav>
        </header>   

        {% block contenido %}

        {% endblock contenido %}

        <br><br>

            <footer class="d-flex flex-wrap justify-content-between align-items-center py-1 my-auto mt-1 border-top bg-success container-fluid">
                <div class="col-md-4 mx-1 pt-3 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                        
                    </a>
                    <span class="mb-3 mt-2 mb-md-0s text-dark">&copy; 2023 - CCCC</span>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="mt-2 mx-2"><a class="text-muted" href="https://twitter.com/correntinosclim/" target="_blank"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
                    <li class="mt-2 mx-2"><a class="text-muted" href="https://www.instagram.com/correntinosclim/" target="_blank"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
                    <li class="mt-2 mx-2"><a class="text-muted" href="https://www.facebook.com/correntinoscontraelcambioclimatico/" target="_blank"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
                </ul>
            </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
            
        </script>

    </body>

</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Home{% endblock titulo %}


{% block contenido %}

{% comment %} CARRUSEL: {% endcomment %}

	<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-indicators">
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
		</div>
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="{% static 'img/carousel3.jpg' %}" class="d-block w-100 img-fluid mx-auto" alt="slide1">
				<div class="carousel-caption d-none d-md-block">
					<img src="{% static 'img/logo2.png' %}" alt="imgslide">
				<h3>Bienvenidos a Correntinos Contra el Cambio Climático</h3>
				<p>Algún contenido placeholder representativo para la primera diapositiva.</p>
			</div>
		</div>
		<div class="carousel-item">
			<img src=" {% static 'img/carousel1.jpg' %} " class="d-block w-100 img-fluid mx-auto" alt="slide2">
			<div class="carousel-caption d-none d-md-block">
			<h3>Buena pic en la facu de vete</h3>
			<p>Algún contenido placeholder representativo para la segunda diapositiva.</p>
		</div>
		</div>
		<div class="carousel-item">
			<img src=" {% static 'img/carousel2.jpg' %} " class="d-block w-100 img-fluid mx-auto" alt="slide3">
			<div class="carousel-caption d-none d-md-block">
				<h3>Juntando colillas en la playita</h3>
				<p>Algún contenido placeholder representativo para la tercera diapositiva.</p>
			</div>
		</div>
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Anterior</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Siguiente</span>
		</button>
	</div>

<br>

{% endblock contenido %}

blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Nosotros{% endblock titulo %}


{% block contenido %}
	<h2>Quienes somos: 
		<br>
		Lorem ipsum dolor, sit amet consectetur adipisicing elit. Distinctio, voluptas dolorum earum eaque, minus, nam facilis nobis qui perferendis eos porro. Non alias perferendis tempore, ullam est obcaecati ratione quas. </h2>
{% endblock contenido %}

blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Noticia{% endblock titulo %}

{% block contenido %}
    <br>
    <h3>{{noticia.titulo}}</h3>
    <img src="{{noticia.imagen.url}}" width="600" height="350">
    <p>Fecha : {{noticia.fecha}}</p>
    <p>Categoría : {{noticia.categoria_noticia}}</p>
    <p>{{noticia.cuerpo}}</p>
{% endblock contenido %}

blog/templates/noticias/noticias.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Noticias{% endblock titulo %}

{% block contenido %}
	{% for noti in noticias %}
		<br>
		<h3><a href="{% url 'noticias:detalle' noti.pk %}">{{noti.titulo}}</a></h3>
		<img src="{{noti.imagen.url}}" width="200" height="150">
		<p>Fecha : {{noti.fecha}}</p>
		<p>Categoría : {{noti.categoria_noticia}}</p>
		<br><br>	
	{% endfor %}
{% endblock contenido %}

blog/templates/usuarios/login.html
{% extends 'base.html' %}

{% block titulo %}Iniciar sesión{% endblock titulo %}

{% block contenido %}
			<form method="POST">{%csrf_token%}
				{{form.errors}}
				<input type="text" name="username" placeholder="Usuario">
				<input type="password" name="password" placeholder="Contraseña">

				<input type="submit" name="" value="Enviar">
			</form>
{% endblock %}

blog/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Registro{% endblock titulo %}

{% block contenido %}

<main role="main">
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-9 mx-auto mb-5">
                <form action="" method="post">{% csrf_token %}
                    <h3 class="mb-4">Registro</h3>
                    {{form.as_p}}
                    <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock contenido %}